<script setup>
import { computed, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import UiIcon from "../../components/UiIcon.vue";
import { createLostFound, deleteLostFound, getLostFound } from "../../services/studentApi";

const router = useRouter();
const loading = ref(true); const error = ref(""); const items = ref([]); const kind = ref("all"); const query = ref(""); const show = ref(false); const saving = ref(false);
const form = ref({ kind: "lost", title: "", content: "", location: "", contact: "" });
const filteredItems = computed(() => items.value.filter((item) => `${item.title} ${item.content || ""} ${item.location || ""}`.toLowerCase().includes(query.value.trim().toLowerCase())));
const lostCount = computed(() => items.value.filter((item) => item.kind === "lost").length);
const foundCount = computed(() => items.value.filter((item) => item.kind === "found").length);
function resetForm() { form.value = { kind: "lost", title: "", content: "", location: "", contact: "" }; }
function dateText(value) { if (!value) return "时间待补充"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleDateString("zh-CN", { month: "numeric", day: "numeric" }); }
async function load() { loading.value = true; error.value = ""; try { items.value = await getLostFound(kind.value === "all" ? {} : { kind: kind.value }); } catch (e) { error.value = e.response?.data?.detail || "失物招领加载失败。"; } finally { loading.value = false; } }
async function publish() { if (!form.value.title.trim() || saving.value) return; saving.value = true; error.value = ""; try { await createLostFound(form.value); show.value = false; resetForm(); await load(); } catch (e) { error.value = e.response?.data?.detail || "发布失败。"; } finally { saving.value = false; } }
async function remove(id) { if (!window.confirm("确认删除这条发布吗？")) return; try { await deleteLostFound(id); items.value = items.value.filter((item) => item.id !== id); } catch (e) { error.value = e.response?.data?.detail || "删除失败，请重试。"; } }
function openDetail(id) { router.push(`/lostfound/${id}`); }
onMounted(load);
</script>

<template>
  <main class="student-page page-enter student-tool-page">
    <div class="student-heading"><div><button class="back-link" @click="router.push('/home')"><UiIcon name="PhArrowLeft" />返回首页</button><span class="eyebrow">CAMPUS BOARD / 校园互助</span><h1>失物招领</h1><p>查看校园内公开的寻物和招领信息，也可以发布一条真实记录帮助别人联系你。</p></div><div class="heading-actions"><button class="secondary-button" :disabled="loading" @click="load"><UiIcon name="PhArrowClockwise" />刷新</button><button class="primary-button" @click="show=true"><UiIcon name="PhPlus" />发布信息</button></div></div>
    <div v-if="error" class="student-alert error"><UiIcon name="PhWarningCircle" />{{ error }}<button class="link-button" @click="load">重试</button></div>
    <section class="lost-summary-grid"><article class="lost-summary-main"><span class="tool-summary-icon warm"><UiIcon name="PhMagnifyingGlass" /></span><div><span class="eyebrow">OPEN BOARD</span><h2>先搜索，再联系</h2><p>信息由校园用户发布，联系前请核对物品特征和地点。</p></div></article><article><small>寻物</small><strong>{{ lostCount }}</strong><span>正在寻找的物品</span></article><article><small>招领</small><strong>{{ foundCount }}</strong><span>等待认领的物品</span></article></section>
    <section class="student-toolbar surface lost-toolbar"><div class="search-field"><UiIcon name="PhMagnifyingGlass" /><input v-model="query" name="lostfound-query" placeholder="搜索物品、地点或描述" /></div><div class="segmented"><button v-for="item in [{key:'all',label:'全部'},{key:'lost',label:'寻物'},{key:'found',label:'招领'}]" :key="item.key" :class="{active:kind===item.key}" @click="kind=item.key;load()">{{ item.label }}</button></div><span class="toolbar-count">{{ filteredItems.length }} 条信息</span></section>
    <section v-if="loading" class="student-card-grid lost-grid"><div v-for="i in 4" :key="i" class="student-panel surface list-skeleton"></div></section><section v-else-if="filteredItems.length" class="lost-grid"><article v-for="item in filteredItems" :key="item.id" class="lost-card-rich surface" role="button" tabindex="0" @click="openDetail(item.id)" @keydown.enter="openDetail(item.id)"><div class="lost-card-top"><span class="status-pill" :class="item.kind==='lost'?'warm':'green'">{{ item.kind==='lost'?'寻物':'招领' }}</span><button class="icon-button" aria-label="删除自己的发布" title="删除自己的发布" @click.stop="remove(item.id)"><UiIcon name="PhTrash" /></button></div><div class="lost-card-title"><span class="lost-card-mark" :class="item.kind==='lost'?'warm':'green'"><UiIcon :name="item.kind==='lost'?'PhMagnifyingGlass':'PhCheckCircle'" /></span><h2>{{ item.title }}</h2></div><p>{{ item.content || '暂无详细描述' }}</p><div class="lost-card-meta"><span><UiIcon name="PhMapPin" />{{ item.location || '地点待补充' }}</span><span><UiIcon name="PhClock" />{{ dateText(item.created_at) }}</span></div><footer><span>查看详细信息</span><UiIcon name="PhArrowUpRight" /></footer></article></section><section v-else class="tool-empty surface lost-empty"><span class="tool-empty-icon"><UiIcon name="PhMagnifyingGlass" :size="34" /></span><strong>{{ query ? '没有匹配的信息' : '暂时没有公开信息' }}</strong><p>{{ query ? '换一个关键词，或清空搜索后再试。' : '这里不会展示固定的失物数据，发布后会同步到校园列表。' }}</p><button v-if="!query" class="secondary-button" @click="show=true"><UiIcon name="PhPlus" />发布第一条信息</button></section>
    <div v-if="show" class="student-modal-backdrop" @click.self="show=false"><form class="student-modal tool-modal" @submit.prevent="publish"><div class="student-modal-head"><div><span class="eyebrow">CAMPUS BOARD</span><h2>发布失物信息</h2><p>请尽量写清物品特征、地点和可联系你的方式。</p></div><button type="button" class="icon-button" aria-label="关闭" @click="show=false"><UiIcon name="PhX" /></button></div><label class="student-field">信息类型<select v-model="form.kind" name="lostfound-kind"><option value="lost">寻物</option><option value="found">招领</option></select></label><label class="student-field">标题<input v-model="form.title" name="lostfound-title" required placeholder="例如：在图书馆三楼遗失黑色水杯" /></label><label class="student-field">描述<textarea v-model="form.content" name="lostfound-content" rows="4" placeholder="补充颜色、品牌、时间等特征"></textarea></label><div class="student-form-grid"><label class="student-field">地点<input v-model="form.location" name="lostfound-location" /></label><label class="student-field">联系方式<input v-model="form.contact" name="lostfound-contact" /></label></div><div class="student-modal-actions"><button type="button" class="secondary-button" @click="show=false">取消</button><button class="primary-button" :disabled="saving || !form.title.trim()">{{ saving?'发布中…':'发布信息' }}</button></div></form></div>
  </main>
</template>
