<script setup>
import { onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import UiIcon from "../../components/UiIcon.vue";
import { deleteLostFound, getLostFoundItem } from "../../services/studentApi";

const route = useRoute(); const router = useRouter(); const loading = ref(true); const error = ref(""); const item = ref(null); const removing = ref(false);
function dateText(value) { if (!value) return "时间待补充"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleString("zh-CN"); }
async function load() { loading.value = true; error.value = ""; try { item.value = await getLostFoundItem(route.params.itemId); } catch (e) { error.value = e.response?.data?.detail || "信息详情加载失败。"; } finally { loading.value = false; } }
async function remove() { if (!item.value || !window.confirm("确认删除这条发布吗？")) return; removing.value = true; try { await deleteLostFound(item.value.id); router.replace("/lostfound"); } catch (e) { error.value = e.response?.data?.detail || "删除失败，请重试。"; } finally { removing.value = false; } }
onMounted(load);
</script>

<template>
  <main class="student-page page-enter student-detail-page"><button class="back-link" @click="router.push('/lostfound')"><UiIcon name="PhArrowLeft" />返回失物招领</button><div v-if="loading" class="student-detail-loading"><div class="student-skeleton"></div><div class="student-skeleton"></div></div><div v-else-if="error" class="student-alert error"><UiIcon name="PhWarningCircle" />{{ error }}<button class="link-button" @click="load">重试</button></div><template v-else-if="item"><section class="detail-hero-board surface"><div class="detail-hero-icon" :class="item.kind === 'lost' ? 'warm' : 'green'"><UiIcon :name="item.kind === 'lost' ? 'PhMagnifyingGlass' : 'PhCheckCircle'" :size="30" /></div><div><span class="status-pill" :class="item.kind === 'lost' ? 'warm' : 'green'">{{ item.kind === 'lost' ? '寻物' : '招领' }}</span><h1>{{ item.title }}</h1><p>发布于 {{ dateText(item.created_at) }}</p></div><button class="secondary-button danger-outline" :disabled="removing" @click="remove"><UiIcon name="PhTrash" />{{ removing ? '删除中…' : '删除发布' }}</button></section><section class="detail-two-column"><article class="student-panel surface detail-reading-card"><div class="student-panel-head"><div><span class="eyebrow">DETAILS</span><h2>物品描述</h2></div></div><p class="rich-text detail-reading-text">{{ item.content || '发布者暂未补充更多描述。' }}</p><div class="detail-fact-grid"><div><UiIcon name="PhMapPin" /><span><small>地点</small><strong>{{ item.location || '地点待补充' }}</strong></span></div><div><UiIcon name="PhClock" /><span><small>发布时间</small><strong>{{ dateText(item.created_at) }}</strong></span></div><div><UiIcon name="PhTag" /><span><small>信息状态</small><strong>{{ item.status === 'open' ? '公开中' : item.status }}</strong></span></div><div><UiIcon name="PhUser" /><span><small>发布身份</small><strong>校园用户</strong></span></div></div></article><aside class="tool-side-stack"><section class="student-panel surface contact-card"><span class="tool-summary-icon blue"><UiIcon name="PhChatCircleText" /></span><span class="eyebrow">CONTACT</span><h2>联系发布者</h2><p>{{ item.contact || '发布者暂未留下联系方式，请关注学校允许的联系渠道。' }}</p></section><section class="student-panel surface tool-source-card"><span class="eyebrow">SAFETY NOTE</span><h3>确认物品前请核对</h3><p>先描述物品特征再联系，线下交接尽量选择公共区域，不要公开敏感个人信息。</p></section></aside></section></template></main>
</template>
