<script setup>
import { onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import UiIcon from "../../components/UiIcon.vue";
import { cancelActivityRegistration, getStudentActivity, getActivityRegistration, registerActivity } from "../../services/studentApi";
const route=useRoute(); const router=useRouter(); const loading=ref(true); const error=ref(""); const activity=ref(null); const registration=ref(null); const submitting=ref(false);
function dateText(value){if(!value)return"待发布";const d=new Date(value);return Number.isNaN(d.valueOf())?value:d.toLocaleString("zh-CN");}
async function load(){loading.value=true;error.value="";try{activity.value=await getStudentActivity(route.params.activityId);registration.value=await getActivityRegistration(route.params.activityId);}catch(e){error.value=e.response?.data?.detail||"活动详情加载失败。";}finally{loading.value=false;}}
async function toggle(){if(submitting.value)return;submitting.value=true;try{registration.value=registration.value?.registered?await cancelActivityRegistration(activity.value.id):await registerActivity(activity.value.id);}catch(e){error.value=e.response?.data?.detail||"报名状态更新失败。";}finally{submitting.value=false;}}
onMounted(load);
</script>
<template><main class="student-page page-enter"><button class="back-link" @click="router.push('/campus-activities')"><UiIcon name="PhArrowLeft" />返回活动列表</button><div v-if="loading" class="student-detail-loading"><div class="student-skeleton"></div></div><div v-else-if="error" class="student-alert error"><UiIcon name="PhWarningCircle" />{{ error }}<button class="link-button" @click="load">重试</button></div><article v-else-if="activity" class="activity-detail-layout"><section class="student-panel surface"><div class="activity-detail-kicker"><span class="status-pill blue">{{ activity.category || '校园活动' }}</span><span>{{ activity.author_name || '学校部门' }}</span></div><h1>{{ activity.title }}</h1><p class="detail-description">{{ activity.summary || '欢迎查看本次校园活动详情。' }}</p><div class="activity-info-grid"><div><UiIcon name="PhCalendarBlank" /><span><small>活动时间</small><strong>{{ dateText(activity.starts_at) }}<br v-if="activity.ends_at" />{{ activity.ends_at ? `至 ${dateText(activity.ends_at)}` : '' }}</strong></span></div><div><UiIcon name="PhMapPin" /><span><small>活动地点</small><strong>{{ activity.location || '地点待发布' }}</strong></span></div><div><UiIcon name="PhUsers" /><span><small>报名情况</small><strong>{{ registration?.registered_count ?? '—' }}{{ activity.capacity ? ` / ${activity.capacity}` : '' }} 人</strong></span></div><div><UiIcon name="PhClock" /><span><small>报名截止</small><strong>{{ dateText(activity.registration_deadline) }}</strong></span></div></div><div class="detail-actions"><button class="primary-button" :class="{danger:registration?.registered}" :disabled="submitting" @click="toggle"><UiIcon :name="registration?.registered ? 'PhX' : 'PhCheck'" />{{ submitting ? '提交中…' : registration?.registered ? '取消报名' : '报名参加' }}</button><span v-if="registration?.registered" class="registration-note"><UiIcon name="PhSealCheck" />已报名 · {{ dateText(registration.registered_at) }}</span></div></section><section class="student-panel surface"><span class="eyebrow">活动说明</span><h2>详细内容</h2><div class="rich-text">{{ activity.content || '主办方暂未补充更多说明。' }}</div></section></article></main></template>
