<script setup>
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import UiIcon from "../../components/UiIcon.vue";
import { getLostFound, getServiceRequests } from "../../services/studentApi";
const route=useRoute();const router=useRouter();const loading=ref(true);const error=ref('');const items=ref([]);const section=computed(()=>route.params.section);
const meta=computed(()=>({files:{title:'我的文件',eyebrow:'FILES',desc:'课程附件由教师上传后从课程详情进入；个人文件存储尚未接入学校文件系统。',icon:'PhFiles'},favorites:{title:'我的收藏',eyebrow:'FAVORITES',desc:'收藏接口尚未接入学校统一收藏服务，当前不展示伪造数据。',icon:'PhBookmark'},requests:{title:'申请记录',eyebrow:'REQUESTS',desc:'这里展示你通过办事大厅提交的申请。',icon:'PhClipboardText'},published:{title:'发布记录',eyebrow:'PUBLISHED',desc:'这里展示你发布的失物招领信息。',icon:'PhMegaphone'}}[section.value]||{title:'个人空间',eyebrow:'PROFILE',desc:'',icon:'PhUser'}));
async function load(){loading.value=true;try{items.value=section.value==='requests'?await getServiceRequests():section.value==='published'?await getLostFound({mine:true}):[];}catch(e){error.value=e.response?.data?.detail||'数据加载失败。';}finally{loading.value=false;}}
onMounted(load);
</script>
<template><main class="student-page page-enter"><button class="back-link" @click="router.push('/profile')"><UiIcon name="PhArrowLeft" />返回个人中心</button><div class="student-heading"><div><span class="eyebrow">{{ meta.eyebrow }}</span><h1>{{ meta.title }}</h1><p>{{ meta.desc }}</p></div><button class="secondary-button" @click="load"><UiIcon name="PhArrowClockwise" />刷新</button></div><div v-if="error" class="student-alert error">{{ error }}</div><section v-if="loading" class="student-panel surface"><div class="list-skeleton"></div></section><section v-else class="student-panel surface"><div v-if="items.length" class="request-list"><button v-for="item in items" :key="item.id" class="request-row" @click="section==='requests' ? router.push(`/services/${item.id}`) : null"><span class="row-icon blue"><UiIcon :name="section==='published'?'PhMegaphone':'PhClipboardText'" /></span><span><strong>{{ item.title }}</strong><small>{{ item.status || item.kind }} · {{ item.created_at }}</small></span><UiIcon name="PhCaretRight" /></button></div><div v-else class="student-empty large"><UiIcon :name="meta.icon" :size="42" /><strong>{{ section==='files'?'暂无个人文件':section==='favorites'?'暂无收藏':section==='requests'?'暂无申请记录':'暂无发布记录' }}</strong><span>{{ meta.desc }}</span></div></section></main></template>
