<script setup>
import { onMounted, ref } from "vue";import UiIcon from "../../components/UiIcon.vue";import { createCommunityPost,favoriteCommunityPost,getCommunityPosts,likeCommunityPost } from "../../services/studentApi";
const loading=ref(false),error=ref(""),items=ref([]),query=ref(""),showComposer=ref(false),submitting=ref(false);const form=ref({title:"",content:"",category:"campus",is_anonymous:false,images:[]});
async function load(){loading.value=true;error.value="";try{items.value=(await getCommunityPosts({q:query.value||undefined})).items||[];}catch(e){error.value=e.response?.data?.code==='UNIVERSITY_REQUIRED'?'请先选择你的大学，再进入校园社区。':(e.response?.data?.message||"社区加载失败");}finally{loading.value=false;}}
async function publish(){submitting.value=true;try{await createCommunityPost(form.value);form.value={title:"",content:"",category:"campus",is_anonymous:false,images:[]};showComposer.value=false;await load();}catch(e){error.value=e.response?.data?.message||"发布失败";}finally{submitting.value=false;}}
async function like(item){Object.assign(item,await likeCommunityPost(item.id));} async function favorite(item){Object.assign(item,await favoriteCommunityPost(item.id));} onMounted(load);
</script>
<template><main class="student-page campus-redesign page-enter"><div class="redesign-heading"><div><span class="redesign-kicker">CAMPUSMATE COMMUNITY</span><h1>校园社区</h1><p>只看当前大学的公开讨论、校园生活与同学互助。</p></div><button class="redesign-button primary" @click="showComposer=!showComposer"><UiIcon name="PhPlus"/>发布帖子</button></div>
<form class="v3-search redesign-panel" @submit.prevent="load"><UiIcon name="PhMagnifyingGlass"/><input v-model="query" placeholder="搜索标题或内容"/><button class="redesign-button secondary">搜索</button></form>
<form v-if="showComposer" class="redesign-panel v3-composer" @submit.prevent="publish"><label>标题<input v-model="form.title" required maxlength="120"/></label><label>正文<textarea v-model="form.content" required maxlength="10000" rows="5"></textarea></label><div><select v-model="form.category"><option value="campus">校园</option><option value="study">学习</option><option value="life">生活</option><option value="secondhand">二手闲置</option><option value="question">求助</option></select><label class="v3-check"><input v-model="form.is_anonymous" type="checkbox"/>校园匿名</label><button class="redesign-button primary" :disabled="submitting">{{submitting?'发布中…':'确认发布'}}</button></div></form>
<div v-if="error" class="redesign-alert error"><UiIcon name="PhWarningCircle"/>{{error}}<button @click="load">重试</button></div><div v-if="loading" class="profile-loading"><div class="profile-loading-grid"><i></i><i></i><i></i></div></div>
<div v-else-if="!items.length" class="redesign-panel v3-empty"><UiIcon name="PhChatsCircle" :size="36"/><strong>暂无帖子</strong><span>成为当前大学第一个发起讨论的同学吧。</span></div>
<section v-else class="v3-feed"><article v-for="item in items" :key="item.id" class="redesign-panel v3-post"><header><span class="avatar">{{item.author_name?.slice(0,1)||'同'}}</span><div><strong>{{item.author_name}}</strong><small>{{item.category}} · {{new Date(item.created_at).toLocaleString('zh-CN')}}</small></div></header><h2>{{item.title}}</h2><p>{{item.content}}</p><footer><button @click="like(item)"><UiIcon name="PhHeart"/>{{item.like_count}}</button><button><UiIcon name="PhChatCircle"/>{{item.comment_count}}</button><button @click="favorite(item)"><UiIcon name="PhBookmarkSimple"/>{{item.favorite_count}}</button></footer></article></section></main></template>
