<script setup>
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import UiIcon from "../../components/UiIcon.vue";
import { getCourseDetail, getMySubmission, markAnnouncementRead } from "../../services/studentApi";
const route = useRoute(); const router = useRouter(); const loading = ref(true); const error = ref(""); const detail = ref(null); const tab = ref("overview"); const selectedSubmission = ref(null);
const classes = computed(() => detail.value?.classes || []);
const assignments = computed(() => classes.value.flatMap((item) => (item.assignments || []).map((assignment) => ({ ...assignment, className: item.name }))));
const announcements = computed(() => classes.value.flatMap((item) => (item.announcements || []).map((notice) => ({ ...notice, className: item.name }))));
const courseStats = computed(() => ({ classes: classes.value.length, assignments: assignments.value.length, announcements: announcements.value.length, completed: assignments.value.filter((item) => ["submitted", "graded"].includes(item.submission_status)).length }));
async function load() { loading.value = true; error.value = ""; try { detail.value = await getCourseDetail(route.params.courseId); } catch (e) { error.value = e.response?.data?.detail || "课程详情加载失败。"; } finally { loading.value = false; } }
async function openGrade(assignment) { selectedSubmission.value = null; try { selectedSubmission.value = await getMySubmission(assignment.id); } catch { selectedSubmission.value = { error: "成绩信息暂时无法加载" }; } }
async function readNotice(notice) { if (!notice.has_read) { try { await markAnnouncementRead(notice.id); notice.has_read = true; } catch { /* detail remains readable */ } } }
onMounted(load);
</script>
<template>
  <main class="student-page campus-redesign course-detail-redesign page-enter"><button class="back-link" @click="router.push('/courses')"><UiIcon name="PhArrowLeft" />返回课程列表</button><div v-if="loading" class="student-detail-loading"><div class="student-skeleton"></div><div class="student-skeleton"></div></div><div v-else-if="error" class="student-alert error"><UiIcon name="PhWarningCircle" />{{ error }}<button class="link-button" @click="load">重试</button></div><template v-else-if="detail"><header class="course-detail-hero surface"><div><span class="eyebrow">{{ detail.course.code || "COURSE" }} · {{ detail.course.semester || "当前学期" }}</span><h1>{{ detail.course.name }}</h1><p>{{ detail.course.description || "这门课程的班级通知、作业与资料会集中展示在这里。" }}</p></div><div class="teacher-chip"><div class="avatar small">{{ detail.course.teacher_name?.slice(0, 1) || "师" }}</div><span><small>任课教师</small><strong>{{ detail.course.teacher_name || "未设置" }}</strong></span></div></header><nav class="detail-tabs"><button v-for="item in [{key:'overview',label:'课程概览'},{key:'materials',label:'资料'},{key:'assignments',label:'作业'},{key:'announcements',label:'通知'},{key:'grades',label:'成绩'},{key:'teacher',label:'教师信息'}]" :key="item.key" :class="{active:tab===item.key}" @click="tab=item.key">{{ item.label }}</button></nav>
    <section v-if="tab==='overview'" class="course-detail-overview"><article class="student-panel surface course-structure-panel"><div class="student-panel-head"><div><span class="eyebrow">学习结构</span><h2>班级与作业</h2></div><span class="toolbar-count">{{ courseStats.completed }}/{{ courseStats.assignments }} 已提交</span></div><div class="course-progress-line"><span><i :style="{width: `${courseStats.assignments ? Math.round((courseStats.completed / courseStats.assignments) * 100) : 0}%`}"></i></span><strong>{{ courseStats.assignments ? Math.round((courseStats.completed / courseStats.assignments) * 100) : 0 }}%</strong></div><div v-if="classes.length" class="detail-class-list"><div v-for="item in classes" :key="item.id" class="detail-class"><span class="class-index"><UiIcon name="PhChalkboardTeacher" /></span><div><strong>{{ item.name }}</strong><small>{{ item.class_code || "班级" }} · {{ item.description || "已加入课程班级" }}</small></div><span>{{ item.assignments?.length || 0 }} 项作业</span></div></div><div v-else class="student-empty"><strong>暂无班级信息</strong><span>这门课程暂未返回班级数据。</span></div></article><article class="student-panel surface course-update-panel"><div class="student-panel-head"><div><span class="eyebrow">最近更新</span><h2>课程通知</h2></div><button class="text-button" @click="tab='announcements'">查看全部</button></div><div v-if="announcements.length" class="student-list"><button v-for="notice in announcements.slice(0,4)" :key="notice.id" class="notice-mini" @click="readNotice(notice); tab='announcements'"><span><strong>{{ notice.title }}</strong><small>{{ notice.className }} · {{ notice.published_at || notice.created_at }}</small></span><UiIcon name="PhCaretRight" /></button></div><div v-else class="student-empty"><UiIcon name="PhBell" :size="28" /><strong>暂无课程通知</strong><span>任课教师发布后会显示在这里。</span></div></article><aside class="student-panel surface course-pulse-panel"><span class="eyebrow">COURSE PULSE</span><h2>这门课的内容</h2><div class="course-pulse-stat"><strong>{{ courseStats.classes }}</strong><span>教学班</span></div><div class="course-pulse-stat"><strong>{{ courseStats.assignments }}</strong><span>项作业</span></div><div class="course-pulse-stat"><strong>{{ courseStats.announcements }}</strong><span>条通知</span></div><button class="secondary-button" @click="tab='assignments'">查看作业<UiIcon name="PhArrowRight" /></button></aside></section>
    <section v-else-if="tab==='materials'" class="student-panel surface course-tab-panel"><div class="student-panel-head"><div><span class="eyebrow">课程资料</span><h2>资料与附件</h2><p class="panel-subtitle">从作业和课程内容中汇总可下载的附件。</p></div><span class="toolbar-count">{{ assignments.reduce((total, item) => total + (item.attachments?.length || 0), 0) }} 个文件</span></div><div v-if="assignments.some((item)=>item.attachments?.length)" class="resource-list"><div v-for="assignment in assignments" :key="assignment.id"><h3>{{ assignment.title }}</h3><a v-for="file in assignment.attachments" :key="file.id" :href="`/api/v1/assignments/${assignment.id}/attachments/${file.id}`" target="_blank"><UiIcon name="PhFileText" />{{ file.original_filename }}<small>{{ file.size_bytes ? `${Math.ceil(file.size_bytes/1024)} KB` : "" }}</small></a></div></div><div v-else class="student-empty large"><UiIcon name="PhFiles" :size="40" /><strong>暂无课程资料</strong><span>资料由任课教师上传到作业或课程通知后会出现在这里。</span></div></section>
    <section v-else-if="tab==='assignments'" class="student-panel surface"><div class="student-panel-head"><div><span class="eyebrow">Coursework</span><h2>课程作业</h2></div><span class="toolbar-count">{{ assignments.length }} 项</span></div><div v-if="assignments.length" class="student-list"><button v-for="assignment in assignments" :key="assignment.id" class="student-list-row" @click="router.push(`/tasks/assignment/${assignment.id}`)"><span class="row-icon blue"><UiIcon name="PhFileText" /></span><span class="row-main"><strong>{{ assignment.title }}</strong><small>{{ assignment.className }} · {{ assignment.status === 'closed' ? '已结束' : '可提交' }}</small></span><time>{{ assignment.deadline ? new Date(assignment.deadline).toLocaleString('zh-CN') : '无截止时间' }}</time><UiIcon name="PhCaretRight" /></button></div><div v-else class="student-empty large"><UiIcon name="PhCheckCircle" :size="40" /><strong>暂无作业</strong><span>课程作业发布后会在此处出现。</span></div></section>
    <section v-else-if="tab==='announcements'" class="student-panel surface"><div class="student-panel-head"><div><span class="eyebrow">Class updates</span><h2>课程通知</h2></div></div><div v-if="announcements.length" class="notice-detail-list"><article v-for="notice in announcements" :key="notice.id" class="notice-detail" :class="{unread: !notice.has_read}"><button @click="readNotice(notice)"><span><strong>{{ notice.title }}</strong><small>{{ notice.className }} · {{ notice.author_name || '课程教师' }} · {{ notice.published_at || notice.created_at }}</small></span><UiIcon name="PhCaretDown" /></button><p>{{ notice.content }}</p></article></div><div v-else class="student-empty large"><strong>暂无通知</strong><span>新通知会显示在这里。</span></div></section>
    <section v-else-if="tab==='grades'" class="student-panel surface"><div class="student-panel-head"><div><span class="eyebrow">成绩记录</span><h2>作业成绩</h2></div><span class="toolbar-count">以教师发布结果为准</span></div><div v-if="assignments.length" class="student-list"><button v-for="assignment in assignments" :key="assignment.id" class="student-list-row" @click="openGrade(assignment)"><span class="row-icon green"><UiIcon name="PhChartBar" /></span><span class="row-main"><strong>{{ assignment.title }}</strong><small>{{ assignment.className }}</small></span><span class="score-value">点击查看</span></button></div><div v-if="selectedSubmission" class="inline-result"><strong>提交结果</strong><span>{{ selectedSubmission.score == null ? '尚未评分' : `${selectedSubmission.score} 分` }}</span><small>{{ selectedSubmission.teacher_comment || '教师暂未留下评语。' }}</small></div><div v-else-if="!assignments.length" class="student-empty large"><strong>暂无成绩记录</strong><span>完成作业后，教师发布的成绩会显示在这里。</span></div></section>
    <section v-else class="student-panel surface"><div class="teacher-profile"><div class="avatar large">{{ detail.course.teacher_name?.slice(0,1) || '师' }}</div><div><span class="eyebrow">任课教师</span><h2>{{ detail.course.teacher_name || '未设置教师信息' }}</h2><p>{{ detail.course.description || '教师联系方式与课程说明由学校教务数据提供。' }}</p></div></div><dl class="info-grid"><div><dt>课程代码</dt><dd>{{ detail.course.code || '—' }}</dd></div><div><dt>开课学期</dt><dd>{{ detail.course.semester || '—' }}</dd></div><div><dt>课程状态</dt><dd>{{ detail.course.status }}</dd></div></dl></section>
  </template></main>
</template>
