import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import * as api from "../data/api.js";
import { itemsOf } from "../data/contracts.js";
import { buildCommentTree } from "../data/alignment.js";
import { AsyncState, BackLink, Button, Modal, PageFrame, Panel, SectionHeading } from "../components/Primitives.jsx";
import { Icon } from "../components/Icon.jsx";
import { formatDateTime } from "../utils/date.js";

const dateText = (value) => formatDateTime(value, { dateStyle: "medium", timeStyle: "short" }, "时间待定");
const errorText = (error) => error?.response?.data?.detail || error?.response?.data?.message || error?.message || "操作失败，请稍后重试";

function CommentNode({ item, onReply }) {
  return <article className="comment-row"><span className="avatar avatar-small"><img src={item.author_avatar || "/assets/generated/home-reference-student-avatar.png"} alt="" /></span><div><strong>{item.is_anonymous ? "匿名同学" : item.author_name || "校园用户"}</strong><p>{item.content}</p><small>{dateText(item.created_at)} <button type="button" className="text-link" onClick={() => onReply(item.id)}>回复</button></small>{item.children?.length ? <div className="comment-children">{item.children.map((child) => <CommentNode key={child.id} item={child} onReply={onReply} />)}</div> : null}</div></article>;
}

export default function CommunityDetailPage() {
  const { postId } = useParams(); const navigate = useNavigate();
  const [post, setPost] = useState(null); const [comments, setComments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [comment, setComment] = useState(""); const [anonymous, setAnonymous] = useState(false); const [parent, setParent] = useState(null); const [reportOpen, setReportOpen] = useState(false); const [reason, setReason] = useState("其它"); const [reportDetails, setReportDetails] = useState("");
  async function load() { setLoading(true); setError(""); try { const [nextPost, nextComments] = await Promise.all([api.getCommunityPost(postId), api.getComments(postId)]); setPost(nextPost); setComments(itemsOf(nextComments)); } catch (cause) { setError(errorText(cause)); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [postId]);
  const commentTree = buildCommentTree(comments);
  async function submitComment(event) { event.preventDefault(); if (!comment.trim()) return; try { await api.createComment(postId, { content: comment.trim(), parent_comment_id: parent, is_anonymous: anonymous }); setComment(""); setParent(null); await load(); } catch (cause) { setNotice(errorText(cause)); } }
  async function report() { try { await api.reportPost({ target_id: postId, reason, details: reportDetails.trim() || null }); setReportOpen(false); setReportDetails(""); setNotice("感谢反馈，我们会处理这条内容"); } catch (cause) { setNotice(errorText(cause)); } }
  async function remove() { if (!window.confirm("确认删除这条帖子吗？")) return; try { await api.deleteCommunityPost(postId); navigate("/community", { replace: true }); } catch (cause) { setNotice(errorText(cause)); } }
  async function toggleLike() { try { await (post?.liked ? api.unlikePost(postId) : api.likePost(postId)); await load(); } catch (cause) { setNotice(errorText(cause)); } }
  async function toggleFavorite() { try { await (post?.favorited ? api.unfavoritePost(postId) : api.favoritePost(postId)); await load(); } catch (cause) { setNotice(errorText(cause)); } }
  return <PageFrame eyebrow="Community / Detail" title={post?.title || "帖子详情"} description={post?.category || "校园社区"} actions={<BackLink to="/community">返回社区</BackLink>}><AsyncState loading={loading} error={error} onRetry={load}><div className="grid grid-2 reveal"><Panel><div className="post-detail-meta"><span className="avatar avatar-small"><img src={post?.author_avatar || "/assets/generated/home-reference-student-avatar.png"} alt="" /></span><span><strong>{post?.is_anonymous ? "匿名同学" : post?.author_name || "校园用户"}</strong><small>{dateText(post?.created_at)}</small></span></div><div className="rich-copy post-content">{post?.content || "暂无内容"}</div>{post?.images?.length ? <div className="post-images">{post.images.map((image) => <img key={image} src={api.resolveAssetUrl(image)} alt="帖子配图" width="180" height="130" />)}</div> : null}<div className="post-detail-actions"><Button variant="quiet" onClick={toggleLike}>{post?.liked ? "已点赞" : "点赞"} {post?.like_count || 0}</Button><Button variant="quiet" onClick={toggleFavorite}>{post?.favorited ? "已收藏" : "收藏"}</Button><Button variant="danger" icon="PhFlag" onClick={() => setReportOpen(true)}>举报</Button>{post?.is_owner && <Button variant="danger" icon="PhTrash" onClick={remove}>删除帖子</Button>}</div>{notice && <div className={`page-notice ${notice.includes("失败") ? "notice-error" : "notice-info"}`} role={notice.includes("失败") ? "alert" : "status"}>{notice}</div>}</Panel><Panel><SectionHeading title="评论" detail={`${comments.length} 条回应`} />{commentTree.length ? <div className="comment-list">{commentTree.map((item) => <CommentNode key={item.id} item={item} onReply={setParent} />)}</div> : <div className="inline-empty">还没有评论，来留下第一条回应。</div>}<form className="comment-form" onSubmit={submitComment}>{parent && <p className="muted-copy">正在回复一条评论 <Button type="button" variant="quiet" onClick={() => setParent(null)}>取消回复</Button></p>}<input required value={comment} onChange={(event) => setComment(event.target.value)} placeholder="写下你的回应…" aria-label="评论内容" /><label className="check-label"><input type="checkbox" checked={anonymous} onChange={(event) => setAnonymous(event.target.checked)} />匿名发表</label><Button icon="PhPaperPlaneRight">发送</Button></form></Panel></div></AsyncState>{reportOpen && <Modal title="举报这条帖子" onClose={() => setReportOpen(false)} actions={<><Button variant="secondary" onClick={() => setReportOpen(false)}>取消</Button><Button variant="danger" onClick={report}>提交举报</Button></>}><div className="stack"><label className="field"><span>举报原因</span><select value={reason} onChange={(event) => setReason(event.target.value)}><option>其它</option><option>垃圾广告</option><option>辱骂攻击</option><option>色情低俗</option><option>违法违规</option><option>隐私泄露</option><option>诈骗</option></select></label><label className="field"><span>补充说明</span><textarea rows="4" value={reportDetails} onChange={(event) => setReportDetails(event.target.value)} placeholder="可选，补充具体问题" /></label></div></Modal>}</PageFrame>;
}
