import { useEffect, useState } from "react";
import * as api from "../data/api.js";
import { agentApi } from "../data/agentApi.js";
import { Button, PageFrame, Panel, SectionHeading } from "../components/Primitives.jsx";
import { itemsOf } from "../data/contracts.js";

export default function CourseResearchPage() {
  const [courses, setCourses] = useState([]); const [courseId, setCourseId] = useState(""); const [question, setQuestion] = useState("");
  const [mode, setMode] = useState("EXPLAIN"); const [allowWeb, setAllowWeb] = useState(false); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { api.getCourses().then((rows) => { const values = itemsOf(rows); setCourses(values); setCourseId(values[0]?.id || ""); }).catch(() => setError("课程加载失败")); }, []);
  async function run(event) { event.preventDefault(); setBusy(true); setError(""); try { setResult(await agentApi.createResearch({ question, course_id: courseId || null, mode, academic_policy: "STANDARD", source_policy: { course_material_priority: true, allow_web: allowWeb, allow_user_upload: false } })); } catch (e) { setError(e?.response?.data?.message || "调研失败"); } finally { setBusy(false); } }
  return <PageFrame className="agent-workspace" eyebrow="Agent / Course Research" title="课程调研工作台" description="课程资料优先；来源未经服务器核验不会进入引用。"><div className="agent-grid"><Panel><SectionHeading title="提出课程问题" detail="策略和风险由服务器裁决" /><form className="stack" onSubmit={run}><select value={courseId} onChange={(e) => setCourseId(e.target.value)} aria-label="选择课程"><option value="">不绑定课程</option>{courses.map((course) => <option value={course.id} key={course.id}>{course.name}</option>)}</select><select value={mode} onChange={(e) => setMode(e.target.value)} aria-label="调研模式"><option value="HINT">只给提示</option><option value="EXPLAIN">概念解释</option><option value="REVIEW">复习梳理</option><option value="FULL_SOLUTION">完整解法申请</option></select><textarea required minLength="2" maxLength="4000" rows="8" value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="例如：为什么数组名在不同表达式中表现不同？" /><label className="check-label"><input type="checkbox" checked={allowWeb} onChange={(e) => setAllowWeb(e.target.checked)} />允许使用公开网页（缺少 provider 时会明确降级）</label><Button disabled={busy || question.trim().length < 2}>{busy ? "调研中…" : "开始受控调研"}</Button></form>{error && <div className="page-notice notice-error">{error}</div>}</Panel>
    <Panel><SectionHeading title="核验结果" detail="只显示安全摘要和受控引用" />{result ? <><div className="agent-badges"><span>{result.status}</span><span>{result.effective_mode}</span><span>{result.academic_policy}</span></div><p>{result.report_summary}</p>{result.warning_codes.map((code) => <div className="page-notice" key={code}>{code}</div>)}<h3>执行角色</h3><div className="agent-role-flow">{result.roles.map((role) => <span key={role}>{role}</span>)}</div><h3>已核验来源</h3><div className="agent-list">{result.sources.map((source) => <div key={source.source_id}><strong>{source.safe_label}</strong><small>{source.source_type} · {source.verification_status}</small></div>)}</div></> : <p className="muted-copy">提交问题后，这里会显示有效策略、执行角色、警告和引用。</p>}</Panel></div></PageFrame>;
}
