<script setup>
import { onMounted, ref, watch } from "vue";
import { getAdminCourses, createAdminCourse, updateAdminCourse } from "../../services/adminRepository";
const rows=ref([]), total=ref(0), page=ref(1), query=ref(""), status=ref(""), loading=ref(true), error=ref(""), saving=ref(false), show=ref(false), toast=ref("");
const form=ref({name:"",code:"",semester:"2026 春",description:"",status:"draft"});
async function load(){loading.value=true;error.value="";try{const r=await getAdminCourses({query:query.value||undefined,status:status.value||undefined,page:page.value});rows.value=r.items;total.value=r.total}catch(e){error.value=e.response?.data?.detail||e.message||"加载失败"}finally{loading.value=false}}
function create(){form.value={name:"",code:"",semester:"2026 春",description:"",status:"draft"};show.value=true}
async function save(){saving.value=true;try{await createAdminCourse(form.value);toast.value="课程已创建";show.value=false;load()}catch(e){toast.value=e.response?.data?.detail||"保存失败"}finally{saving.value=false}}
async function archive(row){if(!confirm(`确认归档“${row.name}”？`))return;try{await updateAdminCourse(row.id,{status:"archived"});toast.value="课程已归档";load()}catch(e){toast.value=e.response?.data?.detail||"操作失败"}}
let timer;watch([query,status],()=>{page.value=1;clearTimeout(timer);timer=setTimeout(load,240)});onMounted(load);
</script>
<template><main class="portal-page admin-portal page-enter"><div v-if="toast" class="portal-toast">{{toast}}</div><div class="portal-heading"><div><span class="portal-kicker">教学资源</span><h1>课程与班级</h1><p>课程状态与授课关系来自真实课程数据，归档只改变可见状态。</p></div><button class="primary-button" @click="create">＋ 创建课程</button></div><section class="portal-toolbar"><div class="portal-search"><input v-model="query" placeholder="搜索课程名称或课程代码" /></div><select v-model="status"><option value="">全部状态</option><option value="draft">草稿</option><option value="active">进行中</option><option value="archived">已归档</option></select><span>{{total}} 门课程</span></section><div v-if="loading" class="portal-loading"><i v-for="n in 4" :key="n"></i></div><div v-else-if="error" class="portal-error">{{error}} <button class="secondary-button" @click="load">重试</button></div><section v-else class="portal-panel account-table"><div class="account-head"><span>课程</span><span>代码 / 学期</span><span>授课教师</span><span>状态</span><span>操作</span></div><article v-for="row in rows" :key="row.id" class="account-row"><div><strong>{{row.name}}</strong><small>{{row.description||"暂无课程简介"}}</small></div><span>{{row.code||"—"}}<small>{{row.semester||"—"}}</small></span><span>{{row.teacher_name||"未分配"}}</span><b>{{row.status}}</b><button v-if="row.status!=='archived'" @click="archive(row)">归档</button></article><div v-if="!rows.length" class="portal-empty">暂无课程数据</div></section><div class="tch-pagination"><button :disabled="page<=1" @click="page--;load()">上一页</button><span>{{page}} / {{Math.max(1,Math.ceil(total/20))}}</span><button :disabled="page>=Math.ceil(total/20)" @click="page++;load()">下一页</button></div><div v-if="show" class="portal-overlay"><form class="portal-drawer" @submit.prevent="save"><div class="drawer-head"><h2>创建课程</h2><button type="button" class="icon-button" @click="show=false">×</button></div><label>课程名称<input v-model="form.name" required /></label><label>课程代码<input v-model="form.code" /></label><label>学期<input v-model="form.semester" /></label><label>课程简介<textarea v-model="form.description" /></label><div class="drawer-actions"><button type="button" class="secondary-button" @click="show=false">取消</button><button class="primary-button" :disabled="saving">{{saving?'保存中…':'创建课程'}}</button></div></form></div></main></template>
