"""教务系统发现/验证状态体系与 Provider 枚举。

状态体系（verification_status）：
- VERIFIED_OFFICIAL : 学校官方网页明确提供该 URL，可自动导入正式 edu_systems。
- VERIFIED_LIVE     : URL 可访问且识别为教务系统，但无学校官方来源，进人工审核。
- CANDIDATE         : 第三方或历史资料发现，不进入生产。
- HISTORICAL        : 明确属于旧系统。
- INTRANET_ONLY     : 10.x / 172.16-31.x / 192.168.x 校内地址。
- DEAD              : 确认长期失效。
- NOT_DISCOVERED    : 暂无数据。

Provider 枚举：
- ZHENGFANG / QIANGZHI / QINGGUO / URP / NEW_URP / SHUWEI / CUSTOM / UNKNOWN

来源类型（source_type）：
- S1_OFFICIAL_PAGE       学校官方页面直接链接
- S2_ACADEMIC_AFFAIRS    学校教务处官方网站
- S3_STUDENT_HANDBOOK    学校官方新生指南/学生手册
- S4_INFO_CENTER         学校官方信息化中心
- S5_OFFICIAL_NOTICE     学校官方通知中的教务链接
- S6_VENDOR_CASE         教务厂商官方案例
- S7_THIRD_PARTY         可靠第三方公开信息（只能 CANDIDATE）
- S8_SEARCH_ENGINE       搜索引擎索引（只能 CANDIDATE）
- S9_GITHUB_PUBLIC       GitHub 公开项目
- S10_WAKEUP_SUPPORTED   WakeUp 已适配名单（仅历史支持证据，不自动 VERIFIED）
- USER_SUBMITTED         用户自行填写 URL（不自动 VERIFIED）
"""
from __future__ import annotations


# ===== Provider 枚举（大写，对外稳定标识） =====
PROVIDER_ZHENGFANG = "ZHENGFANG"
PROVIDER_QIANGZHI = "QIANGZHI"
PROVIDER_QINGGUO = "QINGGUO"
PROVIDER_URP = "URP"
PROVIDER_NEW_URP = "NEW_URP"
PROVIDER_SHUWEI = "SHUWEI"
PROVIDER_CUSTOM = "CUSTOM"
PROVIDER_UNKNOWN = "UNKNOWN"

ALL_PROVIDERS = (
    PROVIDER_ZHENGFANG,
    PROVIDER_QIANGZHI,
    PROVIDER_QINGGUO,
    PROVIDER_URP,
    PROVIDER_NEW_URP,
    PROVIDER_SHUWEI,
    PROVIDER_CUSTOM,
    PROVIDER_UNKNOWN,
)

# 旧小写 provider -> 新大写 provider 映射（兼容旧候选数据）
LEGACY_PROVIDER_MAP = {
    "zhengfang": PROVIDER_ZHENGFANG,
    "qiangzhi": PROVIDER_QIANGZHI,
    "qingguo": PROVIDER_QINGGUO,
    "kingosoft": PROVIDER_QINGGUO,  # 金智(Kingosoft)归入青果系
    "urp": PROVIDER_URP,
    "new_urp": PROVIDER_NEW_URP,
    "shuwei": PROVIDER_SHUWEI,
    "custom": PROVIDER_CUSTOM,
    "unknown": PROVIDER_UNKNOWN,
    "unsupported": PROVIDER_UNKNOWN,
    "mock": PROVIDER_CUSTOM,
}


def normalize_provider(p: str | None) -> str:
    if not p:
        return PROVIDER_UNKNOWN
    p = p.strip()
    if p.upper() in ALL_PROVIDERS:
        return p.upper()
    return LEGACY_PROVIDER_MAP.get(p.lower(), PROVIDER_UNKNOWN)


# ===== 验证状态枚举 =====
STATUS_VERIFIED_OFFICIAL = "VERIFIED_OFFICIAL"
STATUS_VERIFIED_LIVE = "VERIFIED_LIVE"
STATUS_CANDIDATE = "CANDIDATE"
STATUS_HISTORICAL = "HISTORICAL"
STATUS_INTRANET_ONLY = "INTRANET_ONLY"
STATUS_DEAD = "DEAD"
STATUS_NOT_DISCOVERED = "NOT_DISCOVERED"

ALL_VERIFICATION_STATUSES = (
    STATUS_VERIFIED_OFFICIAL,
    STATUS_VERIFIED_LIVE,
    STATUS_CANDIDATE,
    STATUS_HISTORICAL,
    STATUS_INTRANET_ONLY,
    STATUS_DEAD,
    STATUS_NOT_DISCOVERED,
)

# 可自动导入正式 edu_systems 的状态
AUTO_IMPORTABLE_STATUSES = (STATUS_VERIFIED_OFFICIAL,)
# 进人工审核的状态
MANUAL_REVIEW_STATUSES = (STATUS_VERIFIED_LIVE,)
# 不进入生产的状态
NON_PROD_STATUSES = (
    STATUS_CANDIDATE,
    STATUS_HISTORICAL,
    STATUS_INTRANET_ONLY,
    STATUS_DEAD,
    STATUS_NOT_DISCOVERED,
)

# 旧状态 -> 新状态映射（兼容旧候选数据）
LEGACY_STATUS_MAP = {
    "VERIFIED": STATUS_VERIFIED_LIVE,  # 旧 VERIFIED 无官方来源证据，降级为 LIVE
    "LIKELY": STATUS_CANDIDATE,
    "UNVERIFIED": STATUS_CANDIDATE,
    "verified": STATUS_VERIFIED_LIVE,
    "unverified": STATUS_CANDIDATE,
    "failed": STATUS_DEAD,
    "not_discovered": STATUS_NOT_DISCOVERED,
}


def normalize_status(s: str | None) -> str:
    if not s:
        return STATUS_NOT_DISCOVERED
    s = s.strip()
    if s in ALL_VERIFICATION_STATUSES:
        return s
    return LEGACY_STATUS_MAP.get(s, STATUS_CANDIDATE)


# ===== 来源类型 =====
SOURCE_S1_OFFICIAL_PAGE = "S1_OFFICIAL_PAGE"
SOURCE_S2_ACADEMIC_AFFAIRS = "S2_ACADEMIC_AFFAIRS"
SOURCE_S3_STUDENT_HANDBOOK = "S3_STUDENT_HANDBOOK"
SOURCE_S4_INFO_CENTER = "S4_INFO_CENTER"
SOURCE_S5_OFFICIAL_NOTICE = "S5_OFFICIAL_NOTICE"
SOURCE_S6_VENDOR_CASE = "S6_VENDOR_CASE"
SOURCE_S7_THIRD_PARTY = "S7_THIRD_PARTY"
SOURCE_S8_SEARCH_ENGINE = "S8_SEARCH_ENGINE"
SOURCE_S9_GITHUB_PUBLIC = "S9_GITHUB_PUBLIC"
SOURCE_S10_WAKEUP_SUPPORTED = "S10_WAKEUP_SUPPORTED"
SOURCE_USER_SUBMITTED = "USER_SUBMITTED"

# 只能标 CANDIDATE 的来源（无官方来源证据）
CANDIDATE_ONLY_SOURCES = (
    SOURCE_S7_THIRD_PARTY,
    SOURCE_S8_SEARCH_ENGINE,
    SOURCE_S9_GITHUB_PUBLIC,
    SOURCE_S10_WAKEUP_SUPPORTED,
    SOURCE_USER_SUBMITTED,
)

# 可标 VERIFIED_OFFICIAL 的来源（学校官方来源）
OFFICIAL_SOURCES = (
    SOURCE_S1_OFFICIAL_PAGE,
    SOURCE_S2_ACADEMIC_AFFAIRS,
    SOURCE_S3_STUDENT_HANDBOOK,
    SOURCE_S4_INFO_CENTER,
    SOURCE_S5_OFFICIAL_NOTICE,
    SOURCE_S6_VENDOR_CASE,
)


__all__ = [
    "PROVIDER_ZHENGFANG",
    "PROVIDER_QIANGZHI",
    "PROVIDER_QINGGUO",
    "PROVIDER_URP",
    "PROVIDER_NEW_URP",
    "PROVIDER_SHUWEI",
    "PROVIDER_CUSTOM",
    "PROVIDER_UNKNOWN",
    "ALL_PROVIDERS",
    "LEGACY_PROVIDER_MAP",
    "normalize_provider",
    "STATUS_VERIFIED_OFFICIAL",
    "STATUS_VERIFIED_LIVE",
    "STATUS_CANDIDATE",
    "STATUS_HISTORICAL",
    "STATUS_INTRANET_ONLY",
    "STATUS_DEAD",
    "STATUS_NOT_DISCOVERED",
    "ALL_VERIFICATION_STATUSES",
    "AUTO_IMPORTABLE_STATUSES",
    "MANUAL_REVIEW_STATUSES",
    "NON_PROD_STATUSES",
    "LEGACY_STATUS_MAP",
    "normalize_status",
    "SOURCE_S1_OFFICIAL_PAGE",
    "SOURCE_S2_ACADEMIC_AFFAIRS",
    "SOURCE_S3_STUDENT_HANDBOOK",
    "SOURCE_S4_INFO_CENTER",
    "SOURCE_S5_OFFICIAL_NOTICE",
    "SOURCE_S6_VENDOR_CASE",
    "SOURCE_S7_THIRD_PARTY",
    "SOURCE_S8_SEARCH_ENGINE",
    "SOURCE_S9_GITHUB_PUBLIC",
    "SOURCE_S10_WAKEUP_SUPPORTED",
    "SOURCE_USER_SUBMITTED",
    "CANDIDATE_ONLY_SOURCES",
    "OFFICIAL_SOURCES",
]