#!/usr/bin/env node

const fs = require("fs");
const os = require("os");
const path = require("path");
const crypto = require("crypto");

const root = process.cwd();
const artifactsDir = path.join(root, "artifacts");
const reportPath = path.join(artifactsDir, "wechat-preview-report.json");
const qrcodeOutput = path.join(artifactsDir, "wechat-preview-qrcode.jpg");

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch (error) {
    return null;
  }
}

function writeJson(file, data) {
  fs.writeFileSync(file, JSON.stringify(data, null, 2));
}

function packageHasMiniProgramCi() {
  const pkg = readJson(path.join(root, "package.json"));
  if (!pkg) return false;
  const deps = Object.assign({}, pkg.dependencies || {}, pkg.devDependencies || {});
  return Boolean(deps["miniprogram-ci"]);
}

function loadMiniProgramCi() {
  if (!packageHasMiniProgramCi()) {
    throw new Error("Missing dependency miniprogram-ci. Install with: npm install -D miniprogram-ci");
  }
  try {
    return require("miniprogram-ci");
  } catch (error) {
    throw new Error("Cannot require miniprogram-ci. Run dependency install first, for example: npm install");
  }
}

function findProjectConfig(projectPath) {
  const direct = path.join(projectPath, "project.config.json");
  if (fs.existsSync(direct)) return direct;
  const parent = path.join(root, "project.config.json");
  return fs.existsSync(parent) ? parent : "";
}

function resolveProjectPath(config) {
  const candidate = process.env.WECHAT_PROJECT_PATH || config.distRoot || config.miniprogramRoot || config.sourceRoot || "";
  return candidate ? path.resolve(root, candidate) : root;
}

function resolveAppId(config) {
  return process.env.WECHAT_APPID || config.appid || "";
}

function resolveRobot(config) {
  return Number(process.env.WECHAT_ROBOT || config.robot || 1);
}

function resolveDesc(config) {
  if (process.env.WECHAT_DESC) return process.env.WECHAT_DESC;
  if (config.descStrategy === "default") return "Preview generated by Codex WeChat Mini Program automation";
  return `Preview ${new Date().toISOString()}`;
}

function createPrivateKeyFile(config) {
  if (process.env.WECHAT_PRIVATE_KEY) {
    const tempPath = path.join(os.tmpdir(), `wechat-private-${process.pid}-${crypto.randomBytes(8).toString("hex")}.key`);
    fs.writeFileSync(tempPath, process.env.WECHAT_PRIVATE_KEY, { mode: 0o600 });
    return { privateKeyPath: tempPath, temporary: true };
  }

  const configuredPath = process.env.WECHAT_PRIVATE_KEY_PATH || config.privateKeyPath || "";
  if (!configuredPath) {
    throw new Error("Missing upload private key. Set WECHAT_PRIVATE_KEY_PATH or WECHAT_PRIVATE_KEY.");
  }
  const privateKeyPath = path.resolve(root, configuredPath);
  if (!fs.existsSync(privateKeyPath)) {
    throw new Error(`privateKeyPath does not exist: ${privateKeyPath}`);
  }
  return { privateKeyPath, temporary: false };
}

function recordExperience(summary, error) {
  if (process.env.WX_EXPERIENCE_DISABLE === "1") return;
  const ledgerScript = path.join(__dirname, "wechat-experience-ledger.js");
  if (!fs.existsSync(ledgerScript)) return;
  try {
    require("child_process").spawnSync(process.execPath, [
      ledgerScript,
      "record",
      "--kind", "error",
      "--task-type", "deploy-miniprogram",
      "--stage", "preview",
      "--area", "miniprogram-ci",
      "--capability", "preview",
      "--experience", error.includes("private") ? "missing-private-key" : "preview-failure",
      "--severity", "blocker",
      "--framework", "wechat-miniprogram",
      "--task", "preview Mini Program",
      "--command", "npm run wx:preview",
      "--summary", summary,
      "--error", error,
      "--source", "artifacts/wechat-preview-report.json"
    ], { cwd: root, stdio: "ignore", env: Object.assign({}, process.env, { WX_EXPERIENCE_DISABLE: "1" }) });
  } catch (ignore) {
    // Do not mask the original preview error.
  }
}

async function main() {
  ensureDir(artifactsDir);
  const startedAt = new Date().toISOString();
  const report = {
    startedAt,
    finishedAt: "",
    status: "pending",
    qrcodeOutput: path.relative(root, qrcodeOutput),
    projectPath: "",
    appidPresent: false,
    robot: null,
    blockers: [],
    suggestions: [],
    docs: [
      "https://developers.weixin.qq.com/miniprogram/dev/devtools/ci.html",
      "https://www.npmjs.com/package/miniprogram-ci"
    ]
  };
  let tempKeyPath = "";

  try {
    const config = readJson(path.join(root, ".codex", "wechat-miniprogram.config.json")) || {};
    const appid = resolveAppId(config);
    const projectPath = resolveProjectPath(config);
    const robot = resolveRobot(config);
    report.projectPath = path.relative(root, projectPath) || ".";
    report.appidPresent = Boolean(appid);
    report.robot = robot;

    if (!appid) throw new Error("Missing AppID. Set appid in .codex/wechat-miniprogram.config.json or WECHAT_APPID.");
    if (!fs.existsSync(projectPath)) throw new Error(`Project path does not exist: ${projectPath}`);
    if (!findProjectConfig(projectPath)) throw new Error("project.config.json not found. Confirm project path or miniprogramRoot.");

    const key = createPrivateKeyFile(config);
    tempKeyPath = key.temporary ? key.privateKeyPath : "";
    const ci = loadMiniProgramCi();
    const project = new ci.Project({
      appid,
      type: "miniProgram",
      projectPath,
      privateKeyPath: key.privateKeyPath,
      ignores: ["node_modules/**/*", ".git/**/*"]
    });

    await ci.preview({
      project,
      desc: resolveDesc(config),
      robot,
      setting: {},
      qrcodeFormat: "image",
      qrcodeOutputDest: qrcodeOutput,
      onProgressUpdate: (event) => {
        if (event && event.message) console.log(event.message);
      }
    });

    report.status = "ok";
  } catch (error) {
    report.status = "blocked";
    report.blockers.push(error.message);
    report.suggestions.push("Run npm run wx:inspect and npm run wx:validate before preview.");
    report.suggestions.push("Confirm AppID, private key, developer permission, IP whitelist, miniprogram-ci dependency, and project path.");
    recordExperience("Preview failed", error.message);
    process.exitCode = 1;
    console.error(`WeChat preview failed: ${error.message}`);
  } finally {
    if (tempKeyPath) {
      try {
        fs.rmSync(tempKeyPath, { force: true });
      } catch (error) {
        report.suggestions.push("Temporary private key cleanup failed; check OS temp directory permissions.");
      }
    }
    report.finishedAt = new Date().toISOString();
    writeJson(reportPath, report);
    console.log(`WeChat preview report written: ${path.relative(root, reportPath)}`);
    if (report.status === "ok") console.log(`Preview QR code written: ${path.relative(root, qrcodeOutput)}`);
  }
}

main();
