import { appTasks } from '@ohos/hvigor-ohos-plugin';
import * as fs from 'fs';
import * as path from 'path';

function readLocalProps(): Record<string, string> {
  const propsFile: string = path.join(__dirname, 'api.local.properties');
  const out: Record<string, string> = {};
  try {
    if (!fs.existsSync(propsFile)) {
      return out;
    }
    const text: string = fs.readFileSync(propsFile, 'utf8');
    const lines: string[] = text.split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
      const raw: string = lines[i];
      const line: string = raw.trim();
      if (line.length === 0 || line.startsWith('#')) {
        continue;
      }
      const idx: number = line.indexOf('=');
      if (idx < 0) {
        continue;
      }
      const key: string = line.slice(0, idx).trim();
      const value: string = line.slice(idx + 1).trim();
      if (key.length > 0) {
        out[key] = value;
      }
    }
  } catch (e) {
    // 读取失败时静默回退到内置默认值, 保证编译不阻塞。
  }
  return out;
}

function ensureGeneratedApiEnv(): void {
  const props: Record<string, string> = readLocalProps();
  const devHost: string = (props['DEV_HOST'] || '').trim() || '127.0.0.1';
  const prodUrl: string = (props['PROD_API_BASE_URL'] || '').trim();
  const target: string = path.join(__dirname, 'entry', 'src', 'main', 'ets', 'core', 'GeneratedApiEnv.ets');
  const content: string =
    '// AUTO-GENERATED by hvigorfile.ts from harmony/api.local.properties. DO NOT EDIT.\n' +
    '// harmony/api.local.properties 与本文件均被 .gitignore 忽略, 不会纳入版本控制。\n' +
    'export class GeneratedApiEnv {\n' +
    `  static readonly DEV_HOST: string = ${JSON.stringify(devHost)};\n` +
    `  static readonly PROD_API_BASE_URL: string = ${JSON.stringify(prodUrl)};\n` +
    '}\n';
  try {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content, 'utf8');
  } catch (e) {
    // 写入失败时静默, 若已存在旧版本则继续使用。
  }
}

ensureGeneratedApiEnv();

export default { system: appTasks, plugins: [] };
