export function createAppRoutes({ loginView, appShell, loadStudentView }) {
  return [
    { path: "/login", component: loginView, meta: { public: true } },
    {
      path: "/",
      component: appShell,
      children: [
        { path: "", redirect: "/home" },
        { path: "home", component: loadStudentView("StudentHomeView"), meta: { roles: ["student"] } },
        { path: "courses", component: loadStudentView("StudentCoursesView"), meta: { roles: ["student"] } },
        { path: "courses/:courseId", component: loadStudentView("StudentCourseDetailView"), meta: { roles: ["student"] } },
        { path: "tasks", component: loadStudentView("StudentTasksView"), meta: { roles: ["student"] } },
        { path: "tasks/:kind/:id", component: loadStudentView("StudentTaskDetailView"), meta: { roles: ["student"] } },
        { path: "community", component: loadStudentView("StudentCommunityView"), meta: { roles: ["student"] } },
        { path: "community/create", component: loadStudentView("StudentCommunityCreateView"), meta: { roles: ["student"] } },
        { path: "community/:postId", component: loadStudentView("StudentCommunityDetailView"), meta: { roles: ["student"] } },
        { path: "university", component: loadStudentView("StudentUniversityView"), meta: { roles: ["student"] } },
        { path: "counselor", component: loadStudentView("StudentCounselorView"), meta: { roles: ["student"] } },
        { path: "notifications", component: loadStudentView("StudentNotificationsView"), meta: { roles: ["student"] } },
        { path: "announcements/:announcementId", component: loadStudentView("StudentAnnouncementDetailView"), meta: { roles: ["student"] } },
        { path: "study", component: loadStudentView("StudentStudyView"), meta: { roles: ["student"] } },
        { path: "exams", component: loadStudentView("StudentExamsView"), meta: { roles: ["student"] } },
        { path: "exams/:examId", component: loadStudentView("StudentExamDetailView"), meta: { roles: ["student"] } },
        { path: "exams/:examId/edit", component: loadStudentView("StudentExamEditView"), meta: { roles: ["student"] } },
        { path: "services", component: loadStudentView("StudentServicesView"), meta: { roles: ["student"] } },
        { path: "services/:requestId", component: loadStudentView("StudentServiceDetailView"), meta: { roles: ["student"] } },
        { path: "classrooms", component: loadStudentView("StudentClassroomsView"), meta: { roles: ["student"] } },
        { path: "lostfound", component: loadStudentView("StudentLostFoundView"), meta: { roles: ["student"] } },
        { path: "lostfound/:itemId", component: loadStudentView("StudentLostFoundDetailView"), meta: { roles: ["student"] } },
        { path: "profile", component: loadStudentView("StudentProfileView"), meta: { roles: ["student"] } },
        { path: "profile/chaoxing", name: "student-chaoxing", component: loadStudentView("StudentChaoxingView"), meta: { roles: ["student"] } },
        { path: "profile/academic", component: loadStudentView("StudentAcademicView"), meta: { roles: ["student"] } },
        { path: "profile/settings", component: loadStudentView("StudentSettingsView"), meta: { roles: ["student"] } },
        { path: "profile/:section", component: loadStudentView("StudentProfileHubView"), meta: { roles: ["student"] } },
      ],
    },
  ];
}
